### ISSUE TITLE
Unequal heights of grid

### ISSUE THREAD

**Issue by ankitjena** [zairza-cetb/club-website#41]
![Screenshot from 2019-04-25 14-19-30](https://user-images.githubusercontent.com/23580602/56722723-45af8780-6765-11e9-943e-2151a7650d3b.png)

**Comment by aquibbaig** [comment]
`https://github.com/zairza-cetb/club-website.git`

**Comment by aquibbaig** [comment]
Lemme see a fix!

**Comment by agathver** [comment]
Use flexbox!

**Comment by harisumaid** [comment]
![Screenshot from 2019-04-27 18-23-21](https://user-images.githubusercontent.com/37744935/56849997-b8616400-6919-11e9-992b-3d2f97af97ed.png)
container inside the flex is not expanding to 100% of its height

**Comment by harisumaid** [comment]
![Screenshot from 2019-04-27 18-22-58](https://user-images.githubusercontent.com/37744935/56850052-a3390500-691a-11e9-9b51-5ec859bd9034.png)
I tried adding 100% height to each element ,it worked somewhat just fine but the proper alignment of elements inside that container is hindered.

**Comment by ankitjena** [comment]
Suggestion. Take a look at the Card component.

**Comment by ankitjena** [comment]
@harisumaid Suggestion. Take a look at the card component, I think using that along with this will solve this.

**Comment by ankitjena** [comment]
@harisumaid Also make a pr with what you have done, then we can also check. Further commits will be updated in the pr automatically.

**Comment by Raj2367** [comment]
when I changed all fonts into roboto then, this bug got fixed...
![Screenshot (32)](https://user-images.githubusercontent.com/41533712/56855450-ff287b80-6964-11e9-85e5-eb243a303931.png)

**Comment by ankitjena** [comment]
@Raj2367  Did you try it on different screen sizes?

**Comment by ankitjena** [comment]
fixed by @harisumaid
